version: '3.8'

services:
  db:
    image: postgres:14
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=senvo-shipment
      - POSTGRES_USER=senvo
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6380:6379"

  api:
    build:
      context: api
    ports:
      - "5050:5050"
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=postgresql://senvo:password@db:5432/senvo-shipment
      - REDIS_URL=redis://redis:6379/0

  log-consumer:
    build:
      context: log-consumer
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0

networks:
  default:
    name: transport

volumes:
  postgres_data:
